M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date Tue 16 Jan 2024 02:22:27 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-16T14:22:27-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1300
%
G90
G05
T1
X6.475Y-0.8372
X6.6719Y-0.8372
T2
X6.2663Y-0.8372
X6.8805Y-0.8372
T3
X1.395Y-1.7
X1.4Y-4.9
X3.6Y-1.7
X3.6Y-4.9
X4.195Y-1.7
X4.2Y-4.9
X6.4Y-1.7
X6.4Y-4.9
M30
